2023-07-10 20:28:05,149 INFO    StreamThr :35147 [internal.py:wandb_internal():86] W&B internal server running at pid: 35147, started at: 2023-07-10 20:28:05.149138
2023-07-10 20:28:05,153 DEBUG   HandlerThread:35147 [handler.py:handle_request():144] handle_request: status
2023-07-10 20:28:05,155 INFO    WriterThread:35147 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_202805-yfsq07hl/run-yfsq07hl.wandb
2023-07-10 20:28:05,156 DEBUG   SenderThread:35147 [sender.py:send():369] send: header
2023-07-10 20:28:05,156 DEBUG   SenderThread:35147 [sender.py:send():369] send: run
2023-07-10 20:28:07,127 INFO    SenderThread:35147 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_202805-yfsq07hl/files
2023-07-10 20:28:07,128 INFO    SenderThread:35147 [sender.py:_start_run_threads():1100] run started: yfsq07hl with start time 1688992085.148618
2023-07-10 20:28:07,128 DEBUG   SenderThread:35147 [sender.py:send_request():396] send_request: summary_record
2023-07-10 20:28:07,128 INFO    SenderThread:35147 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 20:28:07,134 DEBUG   HandlerThread:35147 [handler.py:handle_request():144] handle_request: check_version
2023-07-10 20:28:07,134 DEBUG   SenderThread:35147 [sender.py:send_request():396] send_request: check_version
2023-07-10 20:28:07,348 DEBUG   HandlerThread:35147 [handler.py:handle_request():144] handle_request: run_start
2023-07-10 20:28:07,356 DEBUG   HandlerThread:35147 [system_info.py:__init__():31] System info init
2023-07-10 20:28:07,357 DEBUG   HandlerThread:35147 [system_info.py:__init__():46] System info init done
2023-07-10 20:28:07,357 INFO    HandlerThread:35147 [system_monitor.py:start():181] Starting system monitor
2023-07-10 20:28:07,358 INFO    HandlerThread:35147 [system_monitor.py:probe():201] Collecting system info
2023-07-10 20:28:07,359 INFO    SystemMonitor:35147 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-10 20:28:07,362 INFO    SystemMonitor:35147 [interfaces.py:start():190] Started cpu monitoring
2023-07-10 20:28:07,365 INFO    SystemMonitor:35147 [interfaces.py:start():190] Started disk monitoring
2023-07-10 20:28:07,367 INFO    SystemMonitor:35147 [interfaces.py:start():190] Started gpu monitoring
2023-07-10 20:28:07,369 INFO    SystemMonitor:35147 [interfaces.py:start():190] Started memory monitoring
2023-07-10 20:28:07,371 INFO    SystemMonitor:35147 [interfaces.py:start():190] Started network monitoring
2023-07-10 20:28:07,382 DEBUG   HandlerThread:35147 [system_info.py:probe():195] Probing system
2023-07-10 20:28:07,387 DEBUG   HandlerThread:35147 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-10 20:28:07,387 DEBUG   HandlerThread:35147 [system_info.py:probe():240] Probing system done
2023-07-10 20:28:07,387 DEBUG   HandlerThread:35147 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-10T12:28:07.382680', 'startedAt': '2023-07-10T12:28:05.140308', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 1958.755125, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 1590.398, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1725.266, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1585.831, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1731.407, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1804.031, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 1515.901, 'min': 800.0, 'max': 5200.0}, {'current': 1513.647, 'min': 800.0, 'max': 5200.0}, {'current': 1538.047, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 1528.136, 'min': 800.0, 'max': 5100.0}, {'current': 1515.102, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 1352.162, 'min': 800.0, 'max': 4100.0}, {'current': 2033.858, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.018306732177734375}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-10 20:28:07,387 INFO    HandlerThread:35147 [system_monitor.py:probe():211] Finished collecting system info
2023-07-10 20:28:07,387 INFO    HandlerThread:35147 [system_monitor.py:probe():214] Publishing system info
2023-07-10 20:28:07,387 DEBUG   HandlerThread:35147 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-10 20:28:07,387 DEBUG   HandlerThread:35147 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-10 20:28:07,388 DEBUG   HandlerThread:35147 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-10 20:28:08,130 INFO    Thread-17 :35147 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_202805-yfsq07hl/files/wandb-summary.json
2023-07-10 20:28:08,130 INFO    Thread-17 :35147 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_202805-yfsq07hl/files/requirements.txt
2023-07-10 20:28:08,131 INFO    Thread-17 :35147 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_202805-yfsq07hl/files/conda-environment.yaml
2023-07-10 20:28:08,256 DEBUG   HandlerThread:35147 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-10 20:28:08,257 INFO    HandlerThread:35147 [system_monitor.py:probe():216] Finished publishing system info
2023-07-10 20:28:08,260 DEBUG   SenderThread:35147 [sender.py:send():369] send: files
2023-07-10 20:28:08,260 INFO    SenderThread:35147 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-10 20:28:08,266 DEBUG   HandlerThread:35147 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 20:28:08,267 DEBUG   SenderThread:35147 [sender.py:send_request():396] send_request: stop_status
2023-07-10 20:28:08,722 ERROR   wandb-upload_0:35147 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/yfsq07hl/wandb-metadata.json?Expires=1689078488&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hCv4NpIGL412otiyPn23caXKY7haonYe0zsWn0xBc5FWFp%2F0uIzLujhylTbR8lRgiuBIUe2sBiTDXZ2imU%2BQBL431lsafIY2q5c7WVfLNkEDOwIWdHaatQ3FPjr3Qg6KVKGRiFklrtgUK%2B6XD%2BCq0bIs6IBv7%2BWY3ie4CtnSRSFPiLo1YSgfHP1IU4mBOJzQ%2BqN7Yn%2BqkGOBWfWx0O6d%2BfPbuye4R%2FpW6CaokTjRzbmj1fj24jftyRa0E%2F%2Bx6cRbjahwtw1kvCxZrir%2B1y9HKEmGNueylFLQUOMVGYMfhzD3pU%2Fyt7hHOLmif%2FDpCDpmzwDskmH9Zu%2B0PWhBH8DEdg%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/yfsq07hl/wandb-metadata.json?Expires=1689078488&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hCv4NpIGL412otiyPn23caXKY7haonYe0zsWn0xBc5FWFp%2F0uIzLujhylTbR8lRgiuBIUe2sBiTDXZ2imU%2BQBL431lsafIY2q5c7WVfLNkEDOwIWdHaatQ3FPjr3Qg6KVKGRiFklrtgUK%2B6XD%2BCq0bIs6IBv7%2BWY3ie4CtnSRSFPiLo1YSgfHP1IU4mBOJzQ%2BqN7Yn%2BqkGOBWfWx0O6d%2BfPbuye4R%2FpW6CaokTjRzbmj1fj24jftyRa0E%2F%2Bx6cRbjahwtw1kvCxZrir%2B1y9HKEmGNueylFLQUOMVGYMfhzD3pU%2Fyt7hHOLmif%2FDpCDpmzwDskmH9Zu%2B0PWhBH8DEdg%3D%3D
2023-07-10 20:28:08,722 ERROR   wandb-upload_0:35147 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3623'}
2023-07-10 20:28:08,722 ERROR   wandb-upload_0:35147 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/yfsq07hl/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 20:28:08,830 DEBUG   SenderThread:35147 [sender.py:send():369] send: telemetry
2023-07-10 20:28:09,130 INFO    Thread-17 :35147 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_202805-yfsq07hl/files/conda-environment.yaml
2023-07-10 20:28:09,130 INFO    Thread-17 :35147 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_202805-yfsq07hl/files/wandb-metadata.json
2023-07-10 20:28:09,131 INFO    Thread-17 :35147 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_202805-yfsq07hl/files/output.log
2023-07-10 20:28:10,727 ERROR   wandb-upload_0:35147 [upload_job.py:push():136] Failed to upload file: /tmp/tmpdzwtlsugwandb/9ou4wo9v-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/yfsq07hl/wandb-metadata.json?Expires=1689078488&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hCv4NpIGL412otiyPn23caXKY7haonYe0zsWn0xBc5FWFp%2F0uIzLujhylTbR8lRgiuBIUe2sBiTDXZ2imU%2BQBL431lsafIY2q5c7WVfLNkEDOwIWdHaatQ3FPjr3Qg6KVKGRiFklrtgUK%2B6XD%2BCq0bIs6IBv7%2BWY3ie4CtnSRSFPiLo1YSgfHP1IU4mBOJzQ%2BqN7Yn%2BqkGOBWfWx0O6d%2BfPbuye4R%2FpW6CaokTjRzbmj1fj24jftyRa0E%2F%2Bx6cRbjahwtw1kvCxZrir%2B1y9HKEmGNueylFLQUOMVGYMfhzD3pU%2Fyt7hHOLmif%2FDpCDpmzwDskmH9Zu%2B0PWhBH8DEdg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 20:28:10,834 DEBUG   HandlerThread:35147 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 20:28:11,131 INFO    Thread-17 :35147 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_202805-yfsq07hl/files/output.log
2023-07-10 20:28:12,734 ERROR   Thread-16 :35147 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpdzwtlsugwandb/9ou4wo9v-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/yfsq07hl/wandb-metadata.json?Expires=1689078488&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=hCv4NpIGL412otiyPn23caXKY7haonYe0zsWn0xBc5FWFp%2F0uIzLujhylTbR8lRgiuBIUe2sBiTDXZ2imU%2BQBL431lsafIY2q5c7WVfLNkEDOwIWdHaatQ3FPjr3Qg6KVKGRiFklrtgUK%2B6XD%2BCq0bIs6IBv7%2BWY3ie4CtnSRSFPiLo1YSgfHP1IU4mBOJzQ%2BqN7Yn%2BqkGOBWfWx0O6d%2BfPbuye4R%2FpW6CaokTjRzbmj1fj24jftyRa0E%2F%2Bx6cRbjahwtw1kvCxZrir%2B1y9HKEmGNueylFLQUOMVGYMfhzD3pU%2Fyt7hHOLmif%2FDpCDpmzwDskmH9Zu%2B0PWhBH8DEdg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 20:28:13,131 INFO    Thread-17 :35147 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_202805-yfsq07hl/files/output.log
2023-07-10 20:28:16,673 DEBUG   HandlerThread:35147 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 20:28:19,134 INFO    Thread-17 :35147 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_202805-yfsq07hl/files/output.log
2023-07-10 20:28:21,136 INFO    Thread-17 :35147 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_202805-yfsq07hl/files/output.log
2023-07-10 20:28:22,616 DEBUG   HandlerThread:35147 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 20:28:23,268 DEBUG   HandlerThread:35147 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 20:28:23,270 DEBUG   SenderThread:35147 [sender.py:send_request():396] send_request: stop_status
2023-07-10 20:28:28,515 DEBUG   HandlerThread:35147 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 20:28:33,517 DEBUG   HandlerThread:35147 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 20:28:38,270 DEBUG   HandlerThread:35147 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 20:28:38,271 DEBUG   SenderThread:35147 [sender.py:send_request():396] send_request: stop_status
2023-07-10 20:28:39,524 DEBUG   HandlerThread:35147 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 20:28:40,151 INFO    Thread-17 :35147 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_202805-yfsq07hl/files/config.yaml
