2023-07-10 17:56:14,795 INFO    StreamThr :10105 [internal.py:wandb_internal():86] W&B internal server running at pid: 10105, started at: 2023-07-10 17:56:14.795537
2023-07-10 17:56:14,797 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: status
2023-07-10 17:56:14,797 INFO    WriterThread:10105 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/run-b2gamged.wandb
2023-07-10 17:56:14,797 DEBUG   SenderThread:10105 [sender.py:send():369] send: header
2023-07-10 17:56:14,797 DEBUG   SenderThread:10105 [sender.py:send():369] send: run
2023-07-10 17:56:15,637 INFO    SenderThread:10105 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files
2023-07-10 17:56:15,638 INFO    SenderThread:10105 [sender.py:_start_run_threads():1100] run started: b2gamged with start time 1688982974.795252
2023-07-10 17:56:15,638 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: summary_record
2023-07-10 17:56:15,638 INFO    SenderThread:10105 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 17:56:15,640 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: check_version
2023-07-10 17:56:15,640 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: check_version
2023-07-10 17:56:15,828 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: run_start
2023-07-10 17:56:15,831 DEBUG   HandlerThread:10105 [system_info.py:__init__():31] System info init
2023-07-10 17:56:15,831 DEBUG   HandlerThread:10105 [system_info.py:__init__():46] System info init done
2023-07-10 17:56:15,831 INFO    HandlerThread:10105 [system_monitor.py:start():181] Starting system monitor
2023-07-10 17:56:15,832 INFO    SystemMonitor:10105 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-10 17:56:15,832 INFO    HandlerThread:10105 [system_monitor.py:probe():201] Collecting system info
2023-07-10 17:56:15,832 INFO    SystemMonitor:10105 [interfaces.py:start():190] Started cpu monitoring
2023-07-10 17:56:15,833 INFO    SystemMonitor:10105 [interfaces.py:start():190] Started disk monitoring
2023-07-10 17:56:15,833 INFO    SystemMonitor:10105 [interfaces.py:start():190] Started gpu monitoring
2023-07-10 17:56:15,833 INFO    SystemMonitor:10105 [interfaces.py:start():190] Started memory monitoring
2023-07-10 17:56:15,834 INFO    SystemMonitor:10105 [interfaces.py:start():190] Started network monitoring
2023-07-10 17:56:15,848 DEBUG   HandlerThread:10105 [system_info.py:probe():195] Probing system
2023-07-10 17:56:15,851 DEBUG   HandlerThread:10105 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-10 17:56:15,851 DEBUG   HandlerThread:10105 [system_info.py:probe():240] Probing system done
2023-07-10 17:56:15,851 DEBUG   HandlerThread:10105 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-10T09:56:15.848641', 'startedAt': '2023-07-10T09:56:14.791919', 'docker': None, 'cuda': None, 'args': ('--phase', 'train', '--gpu_ids', '1'), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3334.1115000000004, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 5100.18, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5099.578, 'min': 800.0, 'max': 5100.0}, {'current': 5015.914, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 4852.752, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5093.928, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5056.324, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.017459869384765625}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-10 17:56:15,851 INFO    HandlerThread:10105 [system_monitor.py:probe():211] Finished collecting system info
2023-07-10 17:56:15,851 INFO    HandlerThread:10105 [system_monitor.py:probe():214] Publishing system info
2023-07-10 17:56:15,851 DEBUG   HandlerThread:10105 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-10 17:56:15,851 DEBUG   HandlerThread:10105 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-10 17:56:15,851 DEBUG   HandlerThread:10105 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-10 17:56:16,638 INFO    Thread-12 :10105 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/wandb-summary.json
2023-07-10 17:56:16,639 INFO    Thread-12 :10105 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/conda-environment.yaml
2023-07-10 17:56:16,639 INFO    Thread-12 :10105 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/requirements.txt
2023-07-10 17:56:16,732 DEBUG   HandlerThread:10105 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-10 17:56:16,732 INFO    HandlerThread:10105 [system_monitor.py:probe():216] Finished publishing system info
2023-07-10 17:56:16,735 DEBUG   SenderThread:10105 [sender.py:send():369] send: files
2023-07-10 17:56:16,735 INFO    SenderThread:10105 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-10 17:56:16,737 DEBUG   SenderThread:10105 [sender.py:send():369] send: telemetry
2023-07-10 17:56:16,778 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 17:56:16,778 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: stop_status
2023-07-10 17:56:17,192 ERROR   wandb-upload_0:10105 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/wandb-metadata.json?Expires=1689069376&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=GEB4Kmb9DiT8XvDmOdzaXY%2FPpUBSRifgDgZyflQL%2BZ9wQwoZrhHdNpehnBMgH8Vr5bMkPUsjbcw7%2BMLYNmlhTRn9UiEDt%2Bj%2B6N6u3jbpneeU4oRFbBMke5MHbTx0mYGFOMgk34GizIECQYIixtikZh%2F4dZeCBIpXMHCpkWIEoN%2FbF0MMrUHp5B62JQ93lsDY%2FQkQg5Ay1YFnznVlFErphOCMhNsY5gFkiv9ZmSPiLZEN3WOiGHEg9zA%2FAsyUv8C1iV7z1ulMiGEm8eKTo%2FkXCkix4SATiAckxpMqA9ohTe4F1o62g%2Bh%2BpdJUuDdmI2oBiZhQPzNmoADO%2B2Se0t4UwQ%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/wandb-metadata.json?Expires=1689069376&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=GEB4Kmb9DiT8XvDmOdzaXY%2FPpUBSRifgDgZyflQL%2BZ9wQwoZrhHdNpehnBMgH8Vr5bMkPUsjbcw7%2BMLYNmlhTRn9UiEDt%2Bj%2B6N6u3jbpneeU4oRFbBMke5MHbTx0mYGFOMgk34GizIECQYIixtikZh%2F4dZeCBIpXMHCpkWIEoN%2FbF0MMrUHp5B62JQ93lsDY%2FQkQg5Ay1YFnznVlFErphOCMhNsY5gFkiv9ZmSPiLZEN3WOiGHEg9zA%2FAsyUv8C1iV7z1ulMiGEm8eKTo%2FkXCkix4SATiAckxpMqA9ohTe4F1o62g%2Bh%2BpdJUuDdmI2oBiZhQPzNmoADO%2B2Se0t4UwQ%3D%3D
2023-07-10 17:56:17,192 ERROR   wandb-upload_0:10105 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3691'}
2023-07-10 17:56:17,192 ERROR   wandb-upload_0:10105 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 17:56:17,639 INFO    Thread-12 :10105 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/conda-environment.yaml
2023-07-10 17:56:17,639 INFO    Thread-12 :10105 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/wandb-metadata.json
2023-07-10 17:56:17,639 INFO    Thread-12 :10105 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/output.log
2023-07-10 17:56:18,855 ERROR   wandb-upload_0:10105 [upload_job.py:push():136] Failed to upload file: /tmp/tmpdfcu9ddswandb/fsnv9y91-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/wandb-metadata.json?Expires=1689069376&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=GEB4Kmb9DiT8XvDmOdzaXY%2FPpUBSRifgDgZyflQL%2BZ9wQwoZrhHdNpehnBMgH8Vr5bMkPUsjbcw7%2BMLYNmlhTRn9UiEDt%2Bj%2B6N6u3jbpneeU4oRFbBMke5MHbTx0mYGFOMgk34GizIECQYIixtikZh%2F4dZeCBIpXMHCpkWIEoN%2FbF0MMrUHp5B62JQ93lsDY%2FQkQg5Ay1YFnznVlFErphOCMhNsY5gFkiv9ZmSPiLZEN3WOiGHEg9zA%2FAsyUv8C1iV7z1ulMiGEm8eKTo%2FkXCkix4SATiAckxpMqA9ohTe4F1o62g%2Bh%2BpdJUuDdmI2oBiZhQPzNmoADO%2B2Se0t4UwQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 17:56:19,068 ERROR   Thread-11 :10105 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpdfcu9ddswandb/fsnv9y91-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/wandb-metadata.json?Expires=1689069376&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=GEB4Kmb9DiT8XvDmOdzaXY%2FPpUBSRifgDgZyflQL%2BZ9wQwoZrhHdNpehnBMgH8Vr5bMkPUsjbcw7%2BMLYNmlhTRn9UiEDt%2Bj%2B6N6u3jbpneeU4oRFbBMke5MHbTx0mYGFOMgk34GizIECQYIixtikZh%2F4dZeCBIpXMHCpkWIEoN%2FbF0MMrUHp5B62JQ93lsDY%2FQkQg5Ay1YFnznVlFErphOCMhNsY5gFkiv9ZmSPiLZEN3WOiGHEg9zA%2FAsyUv8C1iV7z1ulMiGEm8eKTo%2FkXCkix4SATiAckxpMqA9ohTe4F1o62g%2Bh%2BpdJUuDdmI2oBiZhQPzNmoADO%2B2Se0t4UwQ%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 17:56:19,639 INFO    Thread-12 :10105 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/output.log
2023-07-10 17:56:20,100 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 17:56:21,640 INFO    Thread-12 :10105 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/output.log
2023-07-10 17:56:24,539 DEBUG   SenderThread:10105 [sender.py:send():369] send: telemetry
2023-07-10 17:56:25,607 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 17:56:25,641 INFO    Thread-12 :10105 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/output.log
2023-07-10 17:56:28,574 DEBUG   SenderThread:10105 [sender.py:send():369] send: exit
2023-07-10 17:56:28,574 INFO    SenderThread:10105 [sender.py:send_exit():574] handling exit code: 1
2023-07-10 17:56:28,574 INFO    SenderThread:10105 [sender.py:send_exit():576] handling runtime: 12
2023-07-10 17:56:28,574 INFO    SenderThread:10105 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 17:56:28,574 INFO    SenderThread:10105 [sender.py:send_exit():582] send defer
2023-07-10 17:56:28,575 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: defer
2023-07-10 17:56:28,575 INFO    HandlerThread:10105 [handler.py:handle_request_defer():170] handle defer: 0
2023-07-10 17:56:28,575 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: defer
2023-07-10 17:56:28,575 INFO    SenderThread:10105 [sender.py:send_request_defer():598] handle sender defer: 0
2023-07-10 17:56:28,575 INFO    SenderThread:10105 [sender.py:transition_state():602] send defer: 1
2023-07-10 17:56:28,575 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: defer
2023-07-10 17:56:28,575 INFO    HandlerThread:10105 [handler.py:handle_request_defer():170] handle defer: 1
2023-07-10 17:56:28,575 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: defer
2023-07-10 17:56:28,575 INFO    SenderThread:10105 [sender.py:send_request_defer():598] handle sender defer: 1
2023-07-10 17:56:28,575 INFO    SenderThread:10105 [sender.py:transition_state():602] send defer: 2
2023-07-10 17:56:28,575 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: defer
2023-07-10 17:56:28,575 INFO    HandlerThread:10105 [handler.py:handle_request_defer():170] handle defer: 2
2023-07-10 17:56:28,576 INFO    HandlerThread:10105 [system_monitor.py:finish():190] Stopping system monitor
2023-07-10 17:56:28,576 DEBUG   SystemMonitor:10105 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-10 17:56:28,576 INFO    HandlerThread:10105 [interfaces.py:finish():202] Joined cpu monitor
2023-07-10 17:56:28,576 DEBUG   SystemMonitor:10105 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-07-10 17:56:28,576 INFO    HandlerThread:10105 [interfaces.py:finish():202] Joined disk monitor
2023-07-10 17:56:28,576 DEBUG   SystemMonitor:10105 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-07-10 17:56:28,616 INFO    HandlerThread:10105 [interfaces.py:finish():202] Joined gpu monitor
2023-07-10 17:56:28,617 INFO    HandlerThread:10105 [interfaces.py:finish():202] Joined memory monitor
2023-07-10 17:56:28,617 INFO    HandlerThread:10105 [interfaces.py:finish():202] Joined network monitor
2023-07-10 17:56:28,617 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: defer
2023-07-10 17:56:28,617 INFO    SenderThread:10105 [sender.py:send_request_defer():598] handle sender defer: 2
2023-07-10 17:56:28,617 INFO    SenderThread:10105 [sender.py:transition_state():602] send defer: 3
2023-07-10 17:56:28,617 DEBUG   SenderThread:10105 [sender.py:send():369] send: stats
2023-07-10 17:56:28,617 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: defer
2023-07-10 17:56:28,617 INFO    HandlerThread:10105 [handler.py:handle_request_defer():170] handle defer: 3
2023-07-10 17:56:28,617 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: defer
2023-07-10 17:56:28,618 INFO    SenderThread:10105 [sender.py:send_request_defer():598] handle sender defer: 3
2023-07-10 17:56:28,618 INFO    SenderThread:10105 [sender.py:transition_state():602] send defer: 4
2023-07-10 17:56:28,618 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: defer
2023-07-10 17:56:28,618 INFO    HandlerThread:10105 [handler.py:handle_request_defer():170] handle defer: 4
2023-07-10 17:56:28,618 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: defer
2023-07-10 17:56:28,618 INFO    SenderThread:10105 [sender.py:send_request_defer():598] handle sender defer: 4
2023-07-10 17:56:28,618 INFO    SenderThread:10105 [sender.py:transition_state():602] send defer: 5
2023-07-10 17:56:28,618 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: defer
2023-07-10 17:56:28,618 INFO    HandlerThread:10105 [handler.py:handle_request_defer():170] handle defer: 5
2023-07-10 17:56:28,618 DEBUG   SenderThread:10105 [sender.py:send():369] send: summary
2023-07-10 17:56:28,618 INFO    SenderThread:10105 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 17:56:28,619 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: defer
2023-07-10 17:56:28,619 INFO    SenderThread:10105 [sender.py:send_request_defer():598] handle sender defer: 5
2023-07-10 17:56:28,619 INFO    SenderThread:10105 [sender.py:transition_state():602] send defer: 6
2023-07-10 17:56:28,619 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: defer
2023-07-10 17:56:28,619 INFO    HandlerThread:10105 [handler.py:handle_request_defer():170] handle defer: 6
2023-07-10 17:56:28,619 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: defer
2023-07-10 17:56:28,619 INFO    SenderThread:10105 [sender.py:send_request_defer():598] handle sender defer: 6
2023-07-10 17:56:28,621 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 17:56:28,641 INFO    Thread-12 :10105 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/wandb-summary.json
2023-07-10 17:56:29,403 INFO    SenderThread:10105 [sender.py:transition_state():602] send defer: 7
2023-07-10 17:56:29,404 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: defer
2023-07-10 17:56:29,404 INFO    HandlerThread:10105 [handler.py:handle_request_defer():170] handle defer: 7
2023-07-10 17:56:29,404 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: defer
2023-07-10 17:56:29,404 INFO    SenderThread:10105 [sender.py:send_request_defer():598] handle sender defer: 7
2023-07-10 17:56:29,573 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: poll_exit
2023-07-10 17:56:29,642 INFO    Thread-12 :10105 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/config.yaml
2023-07-10 17:56:29,642 INFO    Thread-12 :10105 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/output.log
2023-07-10 17:56:33,376 INFO    SenderThread:10105 [sender.py:transition_state():602] send defer: 8
2023-07-10 17:56:33,376 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: poll_exit
2023-07-10 17:56:33,376 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: defer
2023-07-10 17:56:33,376 INFO    HandlerThread:10105 [handler.py:handle_request_defer():170] handle defer: 8
2023-07-10 17:56:33,377 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: defer
2023-07-10 17:56:33,377 INFO    SenderThread:10105 [sender.py:send_request_defer():598] handle sender defer: 8
2023-07-10 17:56:33,377 INFO    SenderThread:10105 [job_builder.py:build():232] Attempting to build job artifact
2023-07-10 17:56:33,377 INFO    SenderThread:10105 [job_builder.py:build():266] no source found
2023-07-10 17:56:33,377 INFO    SenderThread:10105 [sender.py:transition_state():602] send defer: 9
2023-07-10 17:56:33,377 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: defer
2023-07-10 17:56:33,377 INFO    HandlerThread:10105 [handler.py:handle_request_defer():170] handle defer: 9
2023-07-10 17:56:33,377 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: defer
2023-07-10 17:56:33,377 INFO    SenderThread:10105 [sender.py:send_request_defer():598] handle sender defer: 9
2023-07-10 17:56:33,377 INFO    SenderThread:10105 [dir_watcher.py:finish():359] shutting down directory watcher
2023-07-10 17:56:33,643 INFO    SenderThread:10105 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/output.log
2023-07-10 17:56:33,643 INFO    SenderThread:10105 [dir_watcher.py:finish():389] scan: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files
2023-07-10 17:56:33,643 INFO    SenderThread:10105 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/wandb-metadata.json wandb-metadata.json
2023-07-10 17:56:33,643 INFO    SenderThread:10105 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/config.yaml config.yaml
2023-07-10 17:56:33,643 INFO    SenderThread:10105 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/requirements.txt requirements.txt
2023-07-10 17:56:33,643 INFO    SenderThread:10105 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/wandb-summary.json wandb-summary.json
2023-07-10 17:56:33,643 INFO    SenderThread:10105 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/conda-environment.yaml conda-environment.yaml
2023-07-10 17:56:33,645 INFO    SenderThread:10105 [dir_watcher.py:finish():403] scan save: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/output.log output.log
2023-07-10 17:56:33,645 INFO    SenderThread:10105 [sender.py:transition_state():602] send defer: 10
2023-07-10 17:56:33,647 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: defer
2023-07-10 17:56:33,647 INFO    HandlerThread:10105 [handler.py:handle_request_defer():170] handle defer: 10
2023-07-10 17:56:33,648 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: defer
2023-07-10 17:56:33,648 INFO    SenderThread:10105 [sender.py:send_request_defer():598] handle sender defer: 10
2023-07-10 17:56:33,648 INFO    SenderThread:10105 [file_pusher.py:finish():159] shutting down file pusher
2023-07-10 17:56:34,103 ERROR   wandb-upload_1:10105 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/requirements.txt?Expires=1689069393&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NLF06ISEtRc6FBm0EC05qmP%2F3H623cnQ4mC7%2FPrax1TXo6BK%2BkcdLWwL5r%2B4z4ylVg%2F9Y0PDo0WqTs0o6Yy8nz0m7%2BZeGPmrP6ksc4NInYGe1pahyMTZc1J1GJD99mwQk%2FhM7Y1qbIcG4XLRnmY%2FQKdb8U7GhdGSvQvx8iZGaOcf6MjurCCz2c5wmvQ09i%2BRH0d5j5ZvCcWyRuEYG4Z%2BIu8Kzoq5nOWHQaTHe%2Flsyi2UDWpk8jvh%2F5Hf9pO85xmMUwntgg9K3rU0271EAllBGgE1Le6AHVhKgasI7RwpCNO54LJJXSL401XNNnoGUa7quqIEt2Vp%2Fc0ZXmc8SV69cA%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/requirements.txt?Expires=1689069393&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NLF06ISEtRc6FBm0EC05qmP%2F3H623cnQ4mC7%2FPrax1TXo6BK%2BkcdLWwL5r%2B4z4ylVg%2F9Y0PDo0WqTs0o6Yy8nz0m7%2BZeGPmrP6ksc4NInYGe1pahyMTZc1J1GJD99mwQk%2FhM7Y1qbIcG4XLRnmY%2FQKdb8U7GhdGSvQvx8iZGaOcf6MjurCCz2c5wmvQ09i%2BRH0d5j5ZvCcWyRuEYG4Z%2BIu8Kzoq5nOWHQaTHe%2Flsyi2UDWpk8jvh%2F5Hf9pO85xmMUwntgg9K3rU0271EAllBGgE1Le6AHVhKgasI7RwpCNO54LJJXSL401XNNnoGUa7quqIEt2Vp%2Fc0ZXmc8SV69cA%3D%3D
2023-07-10 17:56:34,103 ERROR   wandb-upload_1:10105 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '910'}
2023-07-10 17:56:34,103 ERROR   wandb-upload_1:10105 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/requirements.txt</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 17:56:34,135 ERROR   wandb-upload_0:10105 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/config.yaml?Expires=1689069393&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Cr7mNNnLmTuDMngAlj%2BAs%2FT1y0z3DB6YXvUsGf8sB88%2FF%2FOuvULYoKlx%2FcZWcVp9uS614%2FRBqrW3CBXuLKWuOLWf6boIyr5dfJ0hgFwCU4fde6gYEmoZnjUXyjXfxCQEG81xe%2BAh%2BJw70XTWP%2BjNo1YQFqJR3E9sp7m9996qNV%2F9EbMAEkdjXYpSuyh54GHHQ9lrFzU3xxQPFKGpFWEhhQ2oVl0bprkp7%2BdIXKVv%2BsMrgFfSteJdkiQHR80sBAHFr9X7sDEB4VBDDB5kfVTTOtXISmF6he%2FaJhPpXzXMdi8JOg%2F%2Ft5quHiDtXO%2BhY7UbHHiqpXEpIEubGG6%2BEDl1gg%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/config.yaml?Expires=1689069393&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Cr7mNNnLmTuDMngAlj%2BAs%2FT1y0z3DB6YXvUsGf8sB88%2FF%2FOuvULYoKlx%2FcZWcVp9uS614%2FRBqrW3CBXuLKWuOLWf6boIyr5dfJ0hgFwCU4fde6gYEmoZnjUXyjXfxCQEG81xe%2BAh%2BJw70XTWP%2BjNo1YQFqJR3E9sp7m9996qNV%2F9EbMAEkdjXYpSuyh54GHHQ9lrFzU3xxQPFKGpFWEhhQ2oVl0bprkp7%2BdIXKVv%2BsMrgFfSteJdkiQHR80sBAHFr9X7sDEB4VBDDB5kfVTTOtXISmF6he%2FaJhPpXzXMdi8JOg%2F%2Ft5quHiDtXO%2BhY7UbHHiqpXEpIEubGG6%2BEDl1gg%3D%3D
2023-07-10 17:56:34,135 ERROR   wandb-upload_0:10105 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '525'}
2023-07-10 17:56:34,135 ERROR   wandb-upload_0:10105 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/config.yaml</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 17:56:34,429 ERROR   wandb-upload_2:10105 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/wandb-summary.json?Expires=1689069394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=tZhtYTMbakK5382wcuvvCd%2Fl2kKvDaayYxD%2BLncRzN%2FmycgVAdip0ct5c3I6Cct8UeQD5ccAa4deFS2fkXdTeIaRceA%2B94liaDx4b%2F5X8MfOgijo1Y3w3VLPEz%2FOjLGAY1gRtoN2MNvuD5PuH9MRmSjMXVDpchCNuALeZ7My7M0IBUCjM0B%2BAG%2B6kQCfqr%2Bd2VcGIwcEMI4iTso62%2FBQWR6cQsOdSStpzvDkxmyjA1%2BGhGE1bHyxGpDlvWHcTlNNFfteWTmV5qn%2BmHclHvxo%2FWZ1EWeYQOeRdkq9eBUgAa7Vl3fFb6pO%2FAZcf3Gz2JcVa9uSmzDzFl%2FlDFGv7S6ukg%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/wandb-summary.json?Expires=1689069394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=tZhtYTMbakK5382wcuvvCd%2Fl2kKvDaayYxD%2BLncRzN%2FmycgVAdip0ct5c3I6Cct8UeQD5ccAa4deFS2fkXdTeIaRceA%2B94liaDx4b%2F5X8MfOgijo1Y3w3VLPEz%2FOjLGAY1gRtoN2MNvuD5PuH9MRmSjMXVDpchCNuALeZ7My7M0IBUCjM0B%2BAG%2B6kQCfqr%2Bd2VcGIwcEMI4iTso62%2FBQWR6cQsOdSStpzvDkxmyjA1%2BGhGE1bHyxGpDlvWHcTlNNFfteWTmV5qn%2BmHclHvxo%2FWZ1EWeYQOeRdkq9eBUgAa7Vl3fFb6pO%2FAZcf3Gz2JcVa9uSmzDzFl%2FlDFGv7S6ukg%3D%3D
2023-07-10 17:56:34,429 ERROR   wandb-upload_2:10105 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '27'}
2023-07-10 17:56:34,429 ERROR   wandb-upload_2:10105 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/wandb-summary.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 17:56:34,484 ERROR   wandb-upload_4:10105 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/output.log?Expires=1689069394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iQvqCqZ%2BYhw9fX5rrHyxdZtDoBNarK%2FIs7JZrwkhov05Tvvkhft%2Fy7wHXMxYAlkd85pTLvhRZtF71yXOTo4%2B4bYK3qEQrEQNxGXPN5YOKO%2F7yb3AtX5%2BlSEbzDz3UsuT5OlIGeLwwVcb2slNhjRKcKC1SyQulUbPv6Gm0%2FlU0qrl5RNf47ssuaBCRcnXJDlGyNM2vQIK%2F7EMUogk4ZRACR61NX%2BBYHB%2Byb6be258EQLc98bj%2BM5mac6l1dLXKr%2BIxBLGORM7fQRLr40aVxjC1kk72Tbjgk5pQMySJZLN72sdOZLyvI8esvlJ4Qf6aXb6o7pTr0dCzBnlfalY%2BcWUBw%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/output.log?Expires=1689069394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iQvqCqZ%2BYhw9fX5rrHyxdZtDoBNarK%2FIs7JZrwkhov05Tvvkhft%2Fy7wHXMxYAlkd85pTLvhRZtF71yXOTo4%2B4bYK3qEQrEQNxGXPN5YOKO%2F7yb3AtX5%2BlSEbzDz3UsuT5OlIGeLwwVcb2slNhjRKcKC1SyQulUbPv6Gm0%2FlU0qrl5RNf47ssuaBCRcnXJDlGyNM2vQIK%2F7EMUogk4ZRACR61NX%2BBYHB%2Byb6be258EQLc98bj%2BM5mac6l1dLXKr%2BIxBLGORM7fQRLr40aVxjC1kk72Tbjgk5pQMySJZLN72sdOZLyvI8esvlJ4Qf6aXb6o7pTr0dCzBnlfalY%2BcWUBw%3D%3D
2023-07-10 17:56:34,484 ERROR   wandb-upload_4:10105 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '27096'}
2023-07-10 17:56:34,484 ERROR   wandb-upload_4:10105 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/output.log</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 17:56:34,485 ERROR   wandb-upload_3:10105 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/conda-environment.yaml?Expires=1689069394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Gri%2FRRT3r%2BNAeCaD61i2uCHU2OgempjKkBAXhjGJRZv17qWrVDS9SPYzdNYvfvdcl2K27mG%2Bqw1cyevyUEG5dNI5b0ABkt9vNQ2MvscjvxaJeGVLRiYxawprgt1DWLbhf1BpErMoXci%2BxYswEqCFW9ff0lcxq%2BaEXM1r9805YZp6A%2FXbquDtkpelyQQrwzMgRvXnNIv94D7bMQymWkzKsiVEZuaS6rlJfTaYqq92XXnMIx%2Bqwu%2BeFgJhV989jSiexCMAjwLJ%2BqfgdOKhs%2Fc1GdXJ5tfm5tT%2BoVl2I1TjWTC844vq3ztc7QL6DPtjF7MG%2FkqM6mRjxNznVAFIWBPP9A%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/conda-environment.yaml?Expires=1689069394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Gri%2FRRT3r%2BNAeCaD61i2uCHU2OgempjKkBAXhjGJRZv17qWrVDS9SPYzdNYvfvdcl2K27mG%2Bqw1cyevyUEG5dNI5b0ABkt9vNQ2MvscjvxaJeGVLRiYxawprgt1DWLbhf1BpErMoXci%2BxYswEqCFW9ff0lcxq%2BaEXM1r9805YZp6A%2FXbquDtkpelyQQrwzMgRvXnNIv94D7bMQymWkzKsiVEZuaS6rlJfTaYqq92XXnMIx%2Bqwu%2BeFgJhV989jSiexCMAjwLJ%2BqfgdOKhs%2Fc1GdXJ5tfm5tT%2BoVl2I1TjWTC844vq3ztc7QL6DPtjF7MG%2FkqM6mRjxNznVAFIWBPP9A%3D%3D
2023-07-10 17:56:34,485 ERROR   wandb-upload_3:10105 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1903'}
2023-07-10 17:56:34,485 ERROR   wandb-upload_3:10105 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/conda-environment.yaml</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 17:56:34,575 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: keepalive
2023-07-10 17:56:35,146 ERROR   wandb-upload_1:10105 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/requirements.txt
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/requirements.txt?Expires=1689069393&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NLF06ISEtRc6FBm0EC05qmP%2F3H623cnQ4mC7%2FPrax1TXo6BK%2BkcdLWwL5r%2B4z4ylVg%2F9Y0PDo0WqTs0o6Yy8nz0m7%2BZeGPmrP6ksc4NInYGe1pahyMTZc1J1GJD99mwQk%2FhM7Y1qbIcG4XLRnmY%2FQKdb8U7GhdGSvQvx8iZGaOcf6MjurCCz2c5wmvQ09i%2BRH0d5j5ZvCcWyRuEYG4Z%2BIu8Kzoq5nOWHQaTHe%2Flsyi2UDWpk8jvh%2F5Hf9pO85xmMUwntgg9K3rU0271EAllBGgE1Le6AHVhKgasI7RwpCNO54LJJXSL401XNNnoGUa7quqIEt2Vp%2Fc0ZXmc8SV69cA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 17:56:35,146 ERROR   wandb-upload_0:10105 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/config.yaml
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/config.yaml?Expires=1689069393&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Cr7mNNnLmTuDMngAlj%2BAs%2FT1y0z3DB6YXvUsGf8sB88%2FF%2FOuvULYoKlx%2FcZWcVp9uS614%2FRBqrW3CBXuLKWuOLWf6boIyr5dfJ0hgFwCU4fde6gYEmoZnjUXyjXfxCQEG81xe%2BAh%2BJw70XTWP%2BjNo1YQFqJR3E9sp7m9996qNV%2F9EbMAEkdjXYpSuyh54GHHQ9lrFzU3xxQPFKGpFWEhhQ2oVl0bprkp7%2BdIXKVv%2BsMrgFfSteJdkiQHR80sBAHFr9X7sDEB4VBDDB5kfVTTOtXISmF6he%2FaJhPpXzXMdi8JOg%2F%2Ft5quHiDtXO%2BhY7UbHHiqpXEpIEubGG6%2BEDl1gg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 17:56:35,147 ERROR   wandb-upload_2:10105 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/wandb-summary.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/wandb-summary.json?Expires=1689069394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=tZhtYTMbakK5382wcuvvCd%2Fl2kKvDaayYxD%2BLncRzN%2FmycgVAdip0ct5c3I6Cct8UeQD5ccAa4deFS2fkXdTeIaRceA%2B94liaDx4b%2F5X8MfOgijo1Y3w3VLPEz%2FOjLGAY1gRtoN2MNvuD5PuH9MRmSjMXVDpchCNuALeZ7My7M0IBUCjM0B%2BAG%2B6kQCfqr%2Bd2VcGIwcEMI4iTso62%2FBQWR6cQsOdSStpzvDkxmyjA1%2BGhGE1bHyxGpDlvWHcTlNNFfteWTmV5qn%2BmHclHvxo%2FWZ1EWeYQOeRdkq9eBUgAa7Vl3fFb6pO%2FAZcf3Gz2JcVa9uSmzDzFl%2FlDFGv7S6ukg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 17:56:35,147 ERROR   wandb-upload_4:10105 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/output.log
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/output.log?Expires=1689069394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iQvqCqZ%2BYhw9fX5rrHyxdZtDoBNarK%2FIs7JZrwkhov05Tvvkhft%2Fy7wHXMxYAlkd85pTLvhRZtF71yXOTo4%2B4bYK3qEQrEQNxGXPN5YOKO%2F7yb3AtX5%2BlSEbzDz3UsuT5OlIGeLwwVcb2slNhjRKcKC1SyQulUbPv6Gm0%2FlU0qrl5RNf47ssuaBCRcnXJDlGyNM2vQIK%2F7EMUogk4ZRACR61NX%2BBYHB%2Byb6be258EQLc98bj%2BM5mac6l1dLXKr%2BIxBLGORM7fQRLr40aVxjC1kk72Tbjgk5pQMySJZLN72sdOZLyvI8esvlJ4Qf6aXb6o7pTr0dCzBnlfalY%2BcWUBw%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 17:56:35,147 ERROR   wandb-upload_3:10105 [upload_job.py:push():136] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/conda-environment.yaml
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/conda-environment.yaml?Expires=1689069394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Gri%2FRRT3r%2BNAeCaD61i2uCHU2OgempjKkBAXhjGJRZv17qWrVDS9SPYzdNYvfvdcl2K27mG%2Bqw1cyevyUEG5dNI5b0ABkt9vNQ2MvscjvxaJeGVLRiYxawprgt1DWLbhf1BpErMoXci%2BxYswEqCFW9ff0lcxq%2BaEXM1r9805YZp6A%2FXbquDtkpelyQQrwzMgRvXnNIv94D7bMQymWkzKsiVEZuaS6rlJfTaYqq92XXnMIx%2Bqwu%2BeFgJhV989jSiexCMAjwLJ%2BqfgdOKhs%2Fc1GdXJ5tfm5tT%2BoVl2I1TjWTC844vq3ztc7QL6DPtjF7MG%2FkqM6mRjxNznVAFIWBPP9A%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 17:56:36,192 ERROR   Thread-11 :10105 [step_upload.py:_handle_event():200] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/requirements.txt
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/requirements.txt?Expires=1689069393&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=NLF06ISEtRc6FBm0EC05qmP%2F3H623cnQ4mC7%2FPrax1TXo6BK%2BkcdLWwL5r%2B4z4ylVg%2F9Y0PDo0WqTs0o6Yy8nz0m7%2BZeGPmrP6ksc4NInYGe1pahyMTZc1J1GJD99mwQk%2FhM7Y1qbIcG4XLRnmY%2FQKdb8U7GhdGSvQvx8iZGaOcf6MjurCCz2c5wmvQ09i%2BRH0d5j5ZvCcWyRuEYG4Z%2BIu8Kzoq5nOWHQaTHe%2Flsyi2UDWpk8jvh%2F5Hf9pO85xmMUwntgg9K3rU0271EAllBGgE1Le6AHVhKgasI7RwpCNO54LJJXSL401XNNnoGUa7quqIEt2Vp%2Fc0ZXmc8SV69cA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 17:56:36,192 ERROR   Thread-11 :10105 [step_upload.py:_handle_event():200] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/config.yaml
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/config.yaml?Expires=1689069393&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Cr7mNNnLmTuDMngAlj%2BAs%2FT1y0z3DB6YXvUsGf8sB88%2FF%2FOuvULYoKlx%2FcZWcVp9uS614%2FRBqrW3CBXuLKWuOLWf6boIyr5dfJ0hgFwCU4fde6gYEmoZnjUXyjXfxCQEG81xe%2BAh%2BJw70XTWP%2BjNo1YQFqJR3E9sp7m9996qNV%2F9EbMAEkdjXYpSuyh54GHHQ9lrFzU3xxQPFKGpFWEhhQ2oVl0bprkp7%2BdIXKVv%2BsMrgFfSteJdkiQHR80sBAHFr9X7sDEB4VBDDB5kfVTTOtXISmF6he%2FaJhPpXzXMdi8JOg%2F%2Ft5quHiDtXO%2BhY7UbHHiqpXEpIEubGG6%2BEDl1gg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 17:56:36,192 ERROR   Thread-11 :10105 [step_upload.py:_handle_event():200] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/wandb-summary.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/wandb-summary.json?Expires=1689069394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=tZhtYTMbakK5382wcuvvCd%2Fl2kKvDaayYxD%2BLncRzN%2FmycgVAdip0ct5c3I6Cct8UeQD5ccAa4deFS2fkXdTeIaRceA%2B94liaDx4b%2F5X8MfOgijo1Y3w3VLPEz%2FOjLGAY1gRtoN2MNvuD5PuH9MRmSjMXVDpchCNuALeZ7My7M0IBUCjM0B%2BAG%2B6kQCfqr%2Bd2VcGIwcEMI4iTso62%2FBQWR6cQsOdSStpzvDkxmyjA1%2BGhGE1bHyxGpDlvWHcTlNNFfteWTmV5qn%2BmHclHvxo%2FWZ1EWeYQOeRdkq9eBUgAa7Vl3fFb6pO%2FAZcf3Gz2JcVa9uSmzDzFl%2FlDFGv7S6ukg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 17:56:36,192 ERROR   Thread-11 :10105 [step_upload.py:_handle_event():200] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/output.log
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/output.log?Expires=1689069394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=iQvqCqZ%2BYhw9fX5rrHyxdZtDoBNarK%2FIs7JZrwkhov05Tvvkhft%2Fy7wHXMxYAlkd85pTLvhRZtF71yXOTo4%2B4bYK3qEQrEQNxGXPN5YOKO%2F7yb3AtX5%2BlSEbzDz3UsuT5OlIGeLwwVcb2slNhjRKcKC1SyQulUbPv6Gm0%2FlU0qrl5RNf47ssuaBCRcnXJDlGyNM2vQIK%2F7EMUogk4ZRACR61NX%2BBYHB%2Byb6be258EQLc98bj%2BM5mac6l1dLXKr%2BIxBLGORM7fQRLr40aVxjC1kk72Tbjgk5pQMySJZLN72sdOZLyvI8esvlJ4Qf6aXb6o7pTr0dCzBnlfalY%2BcWUBw%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 17:56:36,192 ERROR   Thread-11 :10105 [step_upload.py:_handle_event():200] Failed to upload file: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/files/conda-environment.yaml
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/b2gamged/conda-environment.yaml?Expires=1689069394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Gri%2FRRT3r%2BNAeCaD61i2uCHU2OgempjKkBAXhjGJRZv17qWrVDS9SPYzdNYvfvdcl2K27mG%2Bqw1cyevyUEG5dNI5b0ABkt9vNQ2MvscjvxaJeGVLRiYxawprgt1DWLbhf1BpErMoXci%2BxYswEqCFW9ff0lcxq%2BaEXM1r9805YZp6A%2FXbquDtkpelyQQrwzMgRvXnNIv94D7bMQymWkzKsiVEZuaS6rlJfTaYqq92XXnMIx%2Bqwu%2BeFgJhV989jSiexCMAjwLJ%2BqfgdOKhs%2Fc1GdXJ5tfm5tT%2BoVl2I1TjWTC844vq3ztc7QL6DPtjF7MG%2FkqM6mRjxNznVAFIWBPP9A%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 17:56:36,393 INFO    Thread-11 :10105 [sender.py:transition_state():602] send defer: 11
2023-07-10 17:56:36,393 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: defer
2023-07-10 17:56:36,393 INFO    HandlerThread:10105 [handler.py:handle_request_defer():170] handle defer: 11
2023-07-10 17:56:36,393 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: defer
2023-07-10 17:56:36,393 INFO    SenderThread:10105 [sender.py:send_request_defer():598] handle sender defer: 11
2023-07-10 17:56:36,393 INFO    SenderThread:10105 [file_pusher.py:join():164] waiting for file pusher
2023-07-10 17:56:36,393 INFO    SenderThread:10105 [sender.py:transition_state():602] send defer: 12
2023-07-10 17:56:36,393 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: defer
2023-07-10 17:56:36,393 INFO    HandlerThread:10105 [handler.py:handle_request_defer():170] handle defer: 12
2023-07-10 17:56:36,394 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: defer
2023-07-10 17:56:36,394 INFO    SenderThread:10105 [sender.py:send_request_defer():598] handle sender defer: 12
2023-07-10 17:56:36,647 INFO    SenderThread:10105 [sender.py:transition_state():602] send defer: 13
2023-07-10 17:56:36,648 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: defer
2023-07-10 17:56:36,648 INFO    HandlerThread:10105 [handler.py:handle_request_defer():170] handle defer: 13
2023-07-10 17:56:36,648 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: defer
2023-07-10 17:56:36,648 INFO    SenderThread:10105 [sender.py:send_request_defer():598] handle sender defer: 13
2023-07-10 17:56:36,648 INFO    SenderThread:10105 [sender.py:transition_state():602] send defer: 14
2023-07-10 17:56:36,648 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: defer
2023-07-10 17:56:36,648 INFO    HandlerThread:10105 [handler.py:handle_request_defer():170] handle defer: 14
2023-07-10 17:56:36,648 DEBUG   SenderThread:10105 [sender.py:send():369] send: final
2023-07-10 17:56:36,648 DEBUG   SenderThread:10105 [sender.py:send():369] send: footer
2023-07-10 17:56:36,648 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: defer
2023-07-10 17:56:36,649 INFO    SenderThread:10105 [sender.py:send_request_defer():598] handle sender defer: 14
2023-07-10 17:56:36,649 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: poll_exit
2023-07-10 17:56:36,649 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: server_info
2023-07-10 17:56:36,649 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: get_summary
2023-07-10 17:56:36,649 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: sampled_history
2023-07-10 17:56:36,649 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: poll_exit
2023-07-10 17:56:36,649 DEBUG   SenderThread:10105 [sender.py:send_request():396] send_request: server_info
2023-07-10 17:56:37,106 INFO    MainThread:10105 [wandb_run.py:_footer_history_summary_info():3467] rendering history
2023-07-10 17:56:37,106 INFO    MainThread:10105 [wandb_run.py:_footer_history_summary_info():3499] rendering summary
2023-07-10 17:56:37,106 INFO    MainThread:10105 [wandb_run.py:_footer_sync_info():3426] logging synced files
2023-07-10 17:56:37,106 DEBUG   HandlerThread:10105 [handler.py:handle_request():144] handle_request: shutdown
2023-07-10 17:56:37,107 INFO    HandlerThread:10105 [handler.py:finish():854] shutting down handler
2023-07-10 17:56:37,649 INFO    WriterThread:10105 [datastore.py:close():298] close: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_175614-b2gamged/run-b2gamged.wandb
2023-07-10 17:56:38,106 INFO    SenderThread:10105 [sender.py:finish():1526] shutting down sender
2023-07-10 17:56:38,106 INFO    SenderThread:10105 [file_pusher.py:finish():159] shutting down file pusher
2023-07-10 17:56:38,106 INFO    SenderThread:10105 [file_pusher.py:join():164] waiting for file pusher
