2023-07-10 18:42:24,411 INFO    StreamThr :20428 [internal.py:wandb_internal():86] W&B internal server running at pid: 20428, started at: 2023-07-10 18:42:24.411140
2023-07-10 18:42:24,414 DEBUG   HandlerThread:20428 [handler.py:handle_request():144] handle_request: status
2023-07-10 18:42:24,416 INFO    WriterThread:20428 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184224-1df9v9nr/run-1df9v9nr.wandb
2023-07-10 18:42:24,417 DEBUG   SenderThread:20428 [sender.py:send():369] send: header
2023-07-10 18:42:24,417 DEBUG   SenderThread:20428 [sender.py:send():369] send: run
2023-07-10 18:42:25,274 INFO    SenderThread:20428 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184224-1df9v9nr/files
2023-07-10 18:42:25,274 INFO    SenderThread:20428 [sender.py:_start_run_threads():1100] run started: 1df9v9nr with start time 1688985744.410762
2023-07-10 18:42:25,274 DEBUG   SenderThread:20428 [sender.py:send_request():396] send_request: summary_record
2023-07-10 18:42:25,274 INFO    SenderThread:20428 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 18:42:25,276 DEBUG   HandlerThread:20428 [handler.py:handle_request():144] handle_request: check_version
2023-07-10 18:42:25,276 DEBUG   SenderThread:20428 [sender.py:send_request():396] send_request: check_version
2023-07-10 18:42:25,462 DEBUG   HandlerThread:20428 [handler.py:handle_request():144] handle_request: run_start
2023-07-10 18:42:25,466 DEBUG   HandlerThread:20428 [system_info.py:__init__():31] System info init
2023-07-10 18:42:25,466 DEBUG   HandlerThread:20428 [system_info.py:__init__():46] System info init done
2023-07-10 18:42:25,466 INFO    HandlerThread:20428 [system_monitor.py:start():181] Starting system monitor
2023-07-10 18:42:25,467 INFO    HandlerThread:20428 [system_monitor.py:probe():201] Collecting system info
2023-07-10 18:42:25,468 INFO    SystemMonitor:20428 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-10 18:42:25,469 INFO    SystemMonitor:20428 [interfaces.py:start():190] Started cpu monitoring
2023-07-10 18:42:25,470 INFO    SystemMonitor:20428 [interfaces.py:start():190] Started disk monitoring
2023-07-10 18:42:25,470 INFO    SystemMonitor:20428 [interfaces.py:start():190] Started gpu monitoring
2023-07-10 18:42:25,471 INFO    SystemMonitor:20428 [interfaces.py:start():190] Started memory monitoring
2023-07-10 18:42:25,472 INFO    SystemMonitor:20428 [interfaces.py:start():190] Started network monitoring
2023-07-10 18:42:25,487 DEBUG   HandlerThread:20428 [system_info.py:probe():195] Probing system
2023-07-10 18:42:25,491 DEBUG   HandlerThread:20428 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-10 18:42:25,491 DEBUG   HandlerThread:20428 [system_info.py:probe():240] Probing system done
2023-07-10 18:42:25,491 DEBUG   HandlerThread:20428 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-10T10:42:25.487670', 'startedAt': '2023-07-10T10:42:24.403064', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3537.664125, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.029, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5009.946, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5109.55, 'min': 800.0, 'max': 5100.0}, {'current': 5099.91, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5100.086, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 3699.293, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.01802825927734375}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-10 18:42:25,491 INFO    HandlerThread:20428 [system_monitor.py:probe():211] Finished collecting system info
2023-07-10 18:42:25,491 INFO    HandlerThread:20428 [system_monitor.py:probe():214] Publishing system info
2023-07-10 18:42:25,491 DEBUG   HandlerThread:20428 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-10 18:42:25,491 DEBUG   HandlerThread:20428 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-10 18:42:25,491 DEBUG   HandlerThread:20428 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-10 18:42:26,248 DEBUG   HandlerThread:20428 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-10 18:42:26,250 INFO    HandlerThread:20428 [system_monitor.py:probe():216] Finished publishing system info
2023-07-10 18:42:26,252 DEBUG   SenderThread:20428 [sender.py:send():369] send: files
2023-07-10 18:42:26,253 INFO    SenderThread:20428 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-10 18:42:26,258 DEBUG   HandlerThread:20428 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 18:42:26,259 DEBUG   SenderThread:20428 [sender.py:send_request():396] send_request: stop_status
2023-07-10 18:42:26,277 INFO    Thread-17 :20428 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184224-1df9v9nr/files/wandb-metadata.json
2023-07-10 18:42:26,277 INFO    Thread-17 :20428 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184224-1df9v9nr/files/conda-environment.yaml
2023-07-10 18:42:26,277 INFO    Thread-17 :20428 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184224-1df9v9nr/files/requirements.txt
2023-07-10 18:42:26,277 INFO    Thread-17 :20428 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184224-1df9v9nr/files/wandb-summary.json
2023-07-10 18:42:26,486 DEBUG   SenderThread:20428 [sender.py:send():369] send: telemetry
2023-07-10 18:42:27,082 ERROR   wandb-upload_0:20428 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/1df9v9nr/wandb-metadata.json?Expires=1689072146&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=oJ9ZGM8P%2Fnzyebk1E2WrNBPfKeEYeMHAs5Sz%2BpUHT3JWaTxZ1WVUCHLRm58dSsKV90k3EUiaJf1oKKNdLaue1QggLJgPuYsiwogJjOx%2ByZG68N5tpxsc0gU5oqFsrLZSkmObUQFi1PBASaS%2Fh1xQtG5KuCzSIBCDsTQOM9L3U5rUDSnkU4r%2FCLp6dRNPABeWMWr%2FXkyStO%2FsrnrQA7g68m8sJsEpVMnbV22T%2FXYBM6EfqhrNyUR7nv6NFrlsA6tm%2BsNCEdZDKYrInWKT4EokaEHjLq3TJOIQypLWUQZLTAu7EuOryAFyfZOgmYoekDSMbW7zT2%2Ffzsgd4CImwdDfXg%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/1df9v9nr/wandb-metadata.json?Expires=1689072146&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=oJ9ZGM8P%2Fnzyebk1E2WrNBPfKeEYeMHAs5Sz%2BpUHT3JWaTxZ1WVUCHLRm58dSsKV90k3EUiaJf1oKKNdLaue1QggLJgPuYsiwogJjOx%2ByZG68N5tpxsc0gU5oqFsrLZSkmObUQFi1PBASaS%2Fh1xQtG5KuCzSIBCDsTQOM9L3U5rUDSnkU4r%2FCLp6dRNPABeWMWr%2FXkyStO%2FsrnrQA7g68m8sJsEpVMnbV22T%2FXYBM6EfqhrNyUR7nv6NFrlsA6tm%2BsNCEdZDKYrInWKT4EokaEHjLq3TJOIQypLWUQZLTAu7EuOryAFyfZOgmYoekDSMbW7zT2%2Ffzsgd4CImwdDfXg%3D%3D
2023-07-10 18:42:27,082 ERROR   wandb-upload_0:20428 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3608'}
2023-07-10 18:42:27,082 ERROR   wandb-upload_0:20428 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/1df9v9nr/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 18:42:27,276 INFO    Thread-17 :20428 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184224-1df9v9nr/files/output.log
2023-07-10 18:42:27,658 ERROR   wandb-upload_0:20428 [upload_job.py:push():136] Failed to upload file: /tmp/tmpuknrzvo6wandb/yf02lt2c-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/1df9v9nr/wandb-metadata.json?Expires=1689072146&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=oJ9ZGM8P%2Fnzyebk1E2WrNBPfKeEYeMHAs5Sz%2BpUHT3JWaTxZ1WVUCHLRm58dSsKV90k3EUiaJf1oKKNdLaue1QggLJgPuYsiwogJjOx%2ByZG68N5tpxsc0gU5oqFsrLZSkmObUQFi1PBASaS%2Fh1xQtG5KuCzSIBCDsTQOM9L3U5rUDSnkU4r%2FCLp6dRNPABeWMWr%2FXkyStO%2FsrnrQA7g68m8sJsEpVMnbV22T%2FXYBM6EfqhrNyUR7nv6NFrlsA6tm%2BsNCEdZDKYrInWKT4EokaEHjLq3TJOIQypLWUQZLTAu7EuOryAFyfZOgmYoekDSMbW7zT2%2Ffzsgd4CImwdDfXg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 18:42:27,876 ERROR   Thread-16 :20428 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpuknrzvo6wandb/yf02lt2c-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/1df9v9nr/wandb-metadata.json?Expires=1689072146&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=oJ9ZGM8P%2Fnzyebk1E2WrNBPfKeEYeMHAs5Sz%2BpUHT3JWaTxZ1WVUCHLRm58dSsKV90k3EUiaJf1oKKNdLaue1QggLJgPuYsiwogJjOx%2ByZG68N5tpxsc0gU5oqFsrLZSkmObUQFi1PBASaS%2Fh1xQtG5KuCzSIBCDsTQOM9L3U5rUDSnkU4r%2FCLp6dRNPABeWMWr%2FXkyStO%2FsrnrQA7g68m8sJsEpVMnbV22T%2FXYBM6EfqhrNyUR7nv6NFrlsA6tm%2BsNCEdZDKYrInWKT4EokaEHjLq3TJOIQypLWUQZLTAu7EuOryAFyfZOgmYoekDSMbW7zT2%2Ffzsgd4CImwdDfXg%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 18:42:29,277 INFO    Thread-17 :20428 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184224-1df9v9nr/files/output.log
2023-07-10 18:42:29,576 DEBUG   HandlerThread:20428 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:42:31,355 INFO    Thread-17 :20428 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184224-1df9v9nr/files/output.log
2023-07-10 18:42:33,402 INFO    Thread-17 :20428 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184224-1df9v9nr/files/output.log
2023-07-10 18:42:35,060 DEBUG   HandlerThread:20428 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 18:42:35,816 INFO    Thread-17 :20428 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_184224-1df9v9nr/files/output.log
