2023-07-11 01:00:03,250 INFO    StreamThr :59845 [internal.py:wandb_internal():86] W&B internal server running at pid: 59845, started at: 2023-07-11 01:00:03.249685
2023-07-11 01:00:03,253 DEBUG   HandlerThread:59845 [handler.py:handle_request():144] handle_request: status
2023-07-11 01:00:03,257 INFO    WriterThread:59845 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_010003-zmzepi5l/run-zmzepi5l.wandb
2023-07-11 01:00:03,257 DEBUG   SenderThread:59845 [sender.py:send():369] send: header
2023-07-11 01:00:03,258 DEBUG   SenderThread:59845 [sender.py:send():369] send: run
2023-07-11 01:00:04,338 INFO    SenderThread:59845 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_010003-zmzepi5l/files
2023-07-11 01:00:04,338 INFO    SenderThread:59845 [sender.py:_start_run_threads():1100] run started: zmzepi5l with start time 1689008403.249895
2023-07-11 01:00:04,338 DEBUG   SenderThread:59845 [sender.py:send_request():396] send_request: summary_record
2023-07-11 01:00:04,339 INFO    SenderThread:59845 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-11 01:00:04,343 DEBUG   HandlerThread:59845 [handler.py:handle_request():144] handle_request: check_version
2023-07-11 01:00:04,344 DEBUG   SenderThread:59845 [sender.py:send_request():396] send_request: check_version
2023-07-11 01:00:04,525 DEBUG   HandlerThread:59845 [handler.py:handle_request():144] handle_request: run_start
2023-07-11 01:00:04,529 DEBUG   HandlerThread:59845 [system_info.py:__init__():31] System info init
2023-07-11 01:00:04,529 DEBUG   HandlerThread:59845 [system_info.py:__init__():46] System info init done
2023-07-11 01:00:04,529 INFO    HandlerThread:59845 [system_monitor.py:start():181] Starting system monitor
2023-07-11 01:00:04,530 INFO    HandlerThread:59845 [system_monitor.py:probe():201] Collecting system info
2023-07-11 01:00:04,531 INFO    SystemMonitor:59845 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-11 01:00:04,532 INFO    SystemMonitor:59845 [interfaces.py:start():190] Started cpu monitoring
2023-07-11 01:00:04,533 INFO    SystemMonitor:59845 [interfaces.py:start():190] Started disk monitoring
2023-07-11 01:00:04,534 INFO    SystemMonitor:59845 [interfaces.py:start():190] Started gpu monitoring
2023-07-11 01:00:04,535 INFO    SystemMonitor:59845 [interfaces.py:start():190] Started memory monitoring
2023-07-11 01:00:04,536 INFO    SystemMonitor:59845 [interfaces.py:start():190] Started network monitoring
2023-07-11 01:00:04,546 DEBUG   HandlerThread:59845 [system_info.py:probe():195] Probing system
2023-07-11 01:00:04,550 DEBUG   HandlerThread:59845 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-11 01:00:04,550 DEBUG   HandlerThread:59845 [system_info.py:probe():240] Probing system done
2023-07-11 01:00:04,550 DEBUG   HandlerThread:59845 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-10T17:00:04.546477', 'startedAt': '2023-07-10T17:00:03.239513', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3802.3996249999996, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 5098.986, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5088.215, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.091, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5096.119, 'min': 800.0, 'max': 5200.0}, {'current': 5100.0, 'min': 800.0, 'max': 5200.0}, {'current': 5099.132, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 5143.881, 'min': 800.0, 'max': 5100.0}, {'current': 5110.548, 'min': 800.0, 'max': 5100.0}, {'current': 5100.0, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 3964.165, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.01898956298828125}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185558319091797}}
2023-07-11 01:00:04,550 INFO    HandlerThread:59845 [system_monitor.py:probe():211] Finished collecting system info
2023-07-11 01:00:04,551 INFO    HandlerThread:59845 [system_monitor.py:probe():214] Publishing system info
2023-07-11 01:00:04,551 DEBUG   HandlerThread:59845 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-11 01:00:04,551 DEBUG   HandlerThread:59845 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-11 01:00:04,551 DEBUG   HandlerThread:59845 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-11 01:00:05,341 INFO    Thread-17 :59845 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_010003-zmzepi5l/files/requirements.txt
2023-07-11 01:00:05,341 INFO    Thread-17 :59845 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_010003-zmzepi5l/files/conda-environment.yaml
2023-07-11 01:00:05,341 INFO    Thread-17 :59845 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_010003-zmzepi5l/files/wandb-summary.json
2023-07-11 01:00:05,390 DEBUG   HandlerThread:59845 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-11 01:00:05,392 INFO    HandlerThread:59845 [system_monitor.py:probe():216] Finished publishing system info
2023-07-11 01:00:05,395 DEBUG   SenderThread:59845 [sender.py:send():369] send: files
2023-07-11 01:00:05,395 INFO    SenderThread:59845 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-11 01:00:05,401 DEBUG   HandlerThread:59845 [handler.py:handle_request():144] handle_request: stop_status
2023-07-11 01:00:05,401 DEBUG   SenderThread:59845 [sender.py:send_request():396] send_request: stop_status
2023-07-11 01:00:05,999 ERROR   wandb-upload_0:59845 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/zmzepi5l/wandb-metadata.json?Expires=1689094805&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=qISEypoEENX4dHwKBpAoA0bD8TDVlTPiCp0PRrLXspCiQgJlWYrEyaZq%2FSOWtombanzdTVhUE5q4%2BO3c7XcCMmVh9nnBvHg6RhNl%2FIlT33rse8%2BuWNdx94aBP%2FwZBpPvvQHhfIVWwNSVMpPdgch9dZjAaWemZCpY56V05AGu%2Bs0tOsypsgmH%2FSaNgqe0BTdkleMtGqZu30Q0fFf%2B0opc8dgDssKQjm2oab%2BkFemoxuVXv3kx%2BkvPIoEqqyTH9aXD1W2gYR%2FSb9EjXl%2BZt9OZ%2FAu7j48PzYWnQ%2BSIneXS4%2FNwKQe%2FnVy1Bl4LsHcmz0rJrdwtql8GNb1V4OGNnBr91A%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/zmzepi5l/wandb-metadata.json?Expires=1689094805&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=qISEypoEENX4dHwKBpAoA0bD8TDVlTPiCp0PRrLXspCiQgJlWYrEyaZq%2FSOWtombanzdTVhUE5q4%2BO3c7XcCMmVh9nnBvHg6RhNl%2FIlT33rse8%2BuWNdx94aBP%2FwZBpPvvQHhfIVWwNSVMpPdgch9dZjAaWemZCpY56V05AGu%2Bs0tOsypsgmH%2FSaNgqe0BTdkleMtGqZu30Q0fFf%2B0opc8dgDssKQjm2oab%2BkFemoxuVXv3kx%2BkvPIoEqqyTH9aXD1W2gYR%2FSb9EjXl%2BZt9OZ%2FAu7j48PzYWnQ%2BSIneXS4%2FNwKQe%2FnVy1Bl4LsHcmz0rJrdwtql8GNb1V4OGNnBr91A%3D%3D
2023-07-11 01:00:05,999 ERROR   wandb-upload_0:59845 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3621'}
2023-07-11 01:00:05,999 ERROR   wandb-upload_0:59845 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/zmzepi5l/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-11 01:00:06,026 DEBUG   SenderThread:59845 [sender.py:send():369] send: telemetry
2023-07-11 01:00:06,341 INFO    Thread-17 :59845 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_010003-zmzepi5l/files/output.log
2023-07-11 01:00:06,341 INFO    Thread-17 :59845 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_010003-zmzepi5l/files/wandb-metadata.json
2023-07-11 01:00:06,578 ERROR   wandb-upload_0:59845 [upload_job.py:push():136] Failed to upload file: /tmp/tmpj99ft4ucwandb/15b737am-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/zmzepi5l/wandb-metadata.json?Expires=1689094805&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=qISEypoEENX4dHwKBpAoA0bD8TDVlTPiCp0PRrLXspCiQgJlWYrEyaZq%2FSOWtombanzdTVhUE5q4%2BO3c7XcCMmVh9nnBvHg6RhNl%2FIlT33rse8%2BuWNdx94aBP%2FwZBpPvvQHhfIVWwNSVMpPdgch9dZjAaWemZCpY56V05AGu%2Bs0tOsypsgmH%2FSaNgqe0BTdkleMtGqZu30Q0fFf%2B0opc8dgDssKQjm2oab%2BkFemoxuVXv3kx%2BkvPIoEqqyTH9aXD1W2gYR%2FSb9EjXl%2BZt9OZ%2FAu7j48PzYWnQ%2BSIneXS4%2FNwKQe%2FnVy1Bl4LsHcmz0rJrdwtql8GNb1V4OGNnBr91A%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-11 01:00:06,797 ERROR   Thread-16 :59845 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpj99ft4ucwandb/15b737am-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/zmzepi5l/wandb-metadata.json?Expires=1689094805&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=qISEypoEENX4dHwKBpAoA0bD8TDVlTPiCp0PRrLXspCiQgJlWYrEyaZq%2FSOWtombanzdTVhUE5q4%2BO3c7XcCMmVh9nnBvHg6RhNl%2FIlT33rse8%2BuWNdx94aBP%2FwZBpPvvQHhfIVWwNSVMpPdgch9dZjAaWemZCpY56V05AGu%2Bs0tOsypsgmH%2FSaNgqe0BTdkleMtGqZu30Q0fFf%2B0opc8dgDssKQjm2oab%2BkFemoxuVXv3kx%2BkvPIoEqqyTH9aXD1W2gYR%2FSb9EjXl%2BZt9OZ%2FAu7j48PzYWnQ%2BSIneXS4%2FNwKQe%2FnVy1Bl4LsHcmz0rJrdwtql8GNb1V4OGNnBr91A%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-11 01:00:08,342 INFO    Thread-17 :59845 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_010003-zmzepi5l/files/output.log
2023-07-11 01:00:08,629 DEBUG   HandlerThread:59845 [handler.py:handle_request():144] handle_request: status_report
2023-07-11 01:00:10,344 INFO    Thread-17 :59845 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230711_010003-zmzepi5l/files/output.log
