2023-07-10 15:16:52,384 INFO    StreamThr :39913 [internal.py:wandb_internal():86] W&B internal server running at pid: 39913, started at: 2023-07-10 15:16:52.383686
2023-07-10 15:16:52,389 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: status
2023-07-10 15:16:52,393 INFO    WriterThread:39913 [datastore.py:open_for_write():85] open: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_151652-3tnqz9l7/run-3tnqz9l7.wandb
2023-07-10 15:16:52,394 DEBUG   SenderThread:39913 [sender.py:send():369] send: header
2023-07-10 15:16:52,394 DEBUG   SenderThread:39913 [sender.py:send():369] send: run
2023-07-10 15:16:54,222 INFO    SenderThread:39913 [dir_watcher.py:__init__():211] watching files in: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_151652-3tnqz9l7/files
2023-07-10 15:16:54,222 INFO    SenderThread:39913 [sender.py:_start_run_threads():1100] run started: 3tnqz9l7 with start time 1688973412.384181
2023-07-10 15:16:54,224 DEBUG   SenderThread:39913 [sender.py:send_request():396] send_request: summary_record
2023-07-10 15:16:54,225 INFO    SenderThread:39913 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-07-10 15:16:54,232 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: check_version
2023-07-10 15:16:54,232 DEBUG   SenderThread:39913 [sender.py:send_request():396] send_request: check_version
2023-07-10 15:16:54,458 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: run_start
2023-07-10 15:16:54,465 DEBUG   HandlerThread:39913 [system_info.py:__init__():31] System info init
2023-07-10 15:16:54,465 DEBUG   HandlerThread:39913 [system_info.py:__init__():46] System info init done
2023-07-10 15:16:54,465 INFO    HandlerThread:39913 [system_monitor.py:start():181] Starting system monitor
2023-07-10 15:16:54,466 INFO    HandlerThread:39913 [system_monitor.py:probe():201] Collecting system info
2023-07-10 15:16:54,467 INFO    SystemMonitor:39913 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-07-10 15:16:54,469 INFO    SystemMonitor:39913 [interfaces.py:start():190] Started cpu monitoring
2023-07-10 15:16:54,470 INFO    SystemMonitor:39913 [interfaces.py:start():190] Started disk monitoring
2023-07-10 15:16:54,471 INFO    SystemMonitor:39913 [interfaces.py:start():190] Started gpu monitoring
2023-07-10 15:16:54,472 INFO    SystemMonitor:39913 [interfaces.py:start():190] Started memory monitoring
2023-07-10 15:16:54,474 INFO    SystemMonitor:39913 [interfaces.py:start():190] Started network monitoring
2023-07-10 15:16:54,485 DEBUG   HandlerThread:39913 [system_info.py:probe():195] Probing system
2023-07-10 15:16:54,489 DEBUG   HandlerThread:39913 [gitlib.py:_init_repo():53] git repository is invalid
2023-07-10 15:16:54,489 DEBUG   HandlerThread:39913 [system_info.py:probe():240] Probing system done
2023-07-10 15:16:54,489 DEBUG   HandlerThread:39913 [system_monitor.py:probe():210] {'os': 'Linux-5.19.0-46-generic-x86_64-with-glibc2.35', 'python': '3.9.16', 'heartbeatAt': '2023-07-10T07:16:54.485916', 'startedAt': '2023-07-10T07:16:52.370761', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/zhuhe/HPE-with-Diffusion/main.py', 'codePath': 'main.py', 'host': '415-2', 'username': 'zhuhe', 'executable': '/home/zhuhe/.conda/envs/diffhpe/bin/python', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 4022.635333333334, 'min': 800.0, 'max': 4783.333333333333}, 'cpu_freq_per_core': [{'current': 4699.334, 'min': 800.0, 'max': 5100.0}, {'current': 4618.306, 'min': 800.0, 'max': 5100.0}, {'current': 4688.696, 'min': 800.0, 'max': 5100.0}, {'current': 4798.244, 'min': 800.0, 'max': 5100.0}, {'current': 4643.319, 'min': 800.0, 'max': 5100.0}, {'current': 2100.0, 'min': 800.0, 'max': 5100.0}, {'current': 4698.925, 'min': 800.0, 'max': 5100.0}, {'current': 4740.586, 'min': 800.0, 'max': 5100.0}, {'current': 4655.126, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 4655.147, 'min': 800.0, 'max': 5200.0}, {'current': 2100.0, 'min': 800.0, 'max': 5200.0}, {'current': 4699.627, 'min': 800.0, 'max': 5100.0}, {'current': 4699.428, 'min': 800.0, 'max': 5100.0}, {'current': 4699.624, 'min': 800.0, 'max': 5100.0}, {'current': 4077.944, 'min': 800.0, 'max': 5100.0}, {'current': 3445.968, 'min': 800.0, 'max': 4100.0}, {'current': 3409.107, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 3355.827, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 2100.0, 'min': 800.0, 'max': 4100.0}, {'current': 3699.631, 'min': 800.0, 'max': 4100.0}], 'disk': {'total': 93.31179428100586, 'used': 0.017955780029296875}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 31.185562133789062}}
2023-07-10 15:16:54,490 INFO    HandlerThread:39913 [system_monitor.py:probe():211] Finished collecting system info
2023-07-10 15:16:54,490 INFO    HandlerThread:39913 [system_monitor.py:probe():214] Publishing system info
2023-07-10 15:16:54,490 DEBUG   HandlerThread:39913 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-07-10 15:16:54,490 DEBUG   HandlerThread:39913 [system_info.py:_save_pip():67] Saving pip packages done
2023-07-10 15:16:54,490 DEBUG   HandlerThread:39913 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-07-10 15:16:55,225 INFO    Thread-17 :39913 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_151652-3tnqz9l7/files/requirements.txt
2023-07-10 15:16:55,225 INFO    Thread-17 :39913 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_151652-3tnqz9l7/files/conda-environment.yaml
2023-07-10 15:16:55,225 INFO    Thread-17 :39913 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_151652-3tnqz9l7/files/wandb-summary.json
2023-07-10 15:16:55,580 DEBUG   HandlerThread:39913 [system_info.py:_save_conda():86] Saving conda packages done
2023-07-10 15:16:55,582 INFO    HandlerThread:39913 [system_monitor.py:probe():216] Finished publishing system info
2023-07-10 15:16:55,585 DEBUG   SenderThread:39913 [sender.py:send():369] send: files
2023-07-10 15:16:55,585 INFO    SenderThread:39913 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-07-10 15:16:55,592 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 15:16:55,593 DEBUG   SenderThread:39913 [sender.py:send_request():396] send_request: stop_status
2023-07-10 15:16:56,153 DEBUG   SenderThread:39913 [sender.py:send():369] send: telemetry
2023-07-10 15:16:56,191 ERROR   wandb-upload_0:39913 [internal_api.py:upload_file():2192] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/3tnqz9l7/wandb-metadata.json?Expires=1689059815&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ocx0ArZEc3dNodUf8qGD19DvFjuCUMa%2B%2BvT2w8TlMgxWP5%2B7gg2IPBZmkNarNgv6BPwn0MylngIEN5qrxpQkkzj%2BY6lIWmNPJ4wZJ%2F08xUAxjP4ViERLB0%2FkqCfPtJUBqbgC3S%2FbkLQhg0xwiWBsDP7qhdJYDxn30w%2BYwJV4iEwwxEScBw5NUGwq%2Bxw4stTx%2FFf0EnTcxMPhn7mxluA3OYcnKFXTVJGiNrhIwfWj5lktcE07HYfzxggrj2C7NDNhHn7CP7g75Z6VCsyTypLJau9b2lDGiGKMKfOmEG0t3jZHR7f%2FFaJUCvjRmkVWQVF%2BJwNko6BPmTTNwbLusfRNAA%3D%3D: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/3tnqz9l7/wandb-metadata.json?Expires=1689059815&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ocx0ArZEc3dNodUf8qGD19DvFjuCUMa%2B%2BvT2w8TlMgxWP5%2B7gg2IPBZmkNarNgv6BPwn0MylngIEN5qrxpQkkzj%2BY6lIWmNPJ4wZJ%2F08xUAxjP4ViERLB0%2FkqCfPtJUBqbgC3S%2FbkLQhg0xwiWBsDP7qhdJYDxn30w%2BYwJV4iEwwxEScBw5NUGwq%2Bxw4stTx%2FFf0EnTcxMPhn7mxluA3OYcnKFXTVJGiNrhIwfWj5lktcE07HYfzxggrj2C7NDNhHn7CP7g75Z6VCsyTypLJau9b2lDGiGKMKfOmEG0t3jZHR7f%2FFaJUCvjRmkVWQVF%2BJwNko6BPmTTNwbLusfRNAA%3D%3D
2023-07-10 15:16:56,191 ERROR   wandb-upload_0:39913 [internal_api.py:upload_file():2194] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '3639'}
2023-07-10 15:16:56,191 ERROR   wandb-upload_0:39913 [internal_api.py:upload_file():2196] upload_file response body: b'<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That\xe2\x80\x99s an error.</ins>\n  <p>The requested URL <code>/wandb-production.appspot.com/ada4321/DiffHPE/3tnqz9l7/wandb-metadata.json</code> was not found on this server.  <ins>That\xe2\x80\x99s all we know.</ins>\n'
2023-07-10 15:16:56,223 INFO    Thread-17 :39913 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_151652-3tnqz9l7/files/conda-environment.yaml
2023-07-10 15:16:56,224 INFO    Thread-17 :39913 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_151652-3tnqz9l7/files/wandb-metadata.json
2023-07-10 15:16:56,224 INFO    Thread-17 :39913 [dir_watcher.py:_on_file_created():272] file/dir created: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_151652-3tnqz9l7/files/output.log
2023-07-10 15:16:56,724 ERROR   wandb-upload_0:39913 [upload_job.py:push():136] Failed to upload file: /tmp/tmpdfxm5nzvwandb/eyfvdtet-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/3tnqz9l7/wandb-metadata.json?Expires=1689059815&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ocx0ArZEc3dNodUf8qGD19DvFjuCUMa%2B%2BvT2w8TlMgxWP5%2B7gg2IPBZmkNarNgv6BPwn0MylngIEN5qrxpQkkzj%2BY6lIWmNPJ4wZJ%2F08xUAxjP4ViERLB0%2FkqCfPtJUBqbgC3S%2FbkLQhg0xwiWBsDP7qhdJYDxn30w%2BYwJV4iEwwxEScBw5NUGwq%2Bxw4stTx%2FFf0EnTcxMPhn7mxluA3OYcnKFXTVJGiNrhIwfWj5lktcE07HYfzxggrj2C7NDNhHn7CP7g75Z6VCsyTypLJau9b2lDGiGKMKfOmEG0t3jZHR7f%2FFaJUCvjRmkVWQVF%2BJwNko6BPmTTNwbLusfRNAA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 15:16:56,935 ERROR   Thread-16 :39913 [step_upload.py:_handle_event():200] Failed to upload file: /tmp/tmpdfxm5nzvwandb/eyfvdtet-wandb-metadata.json
Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 212, in wrapped_fn
    return retrier(*args, **kargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2218, in upload_file
    wandb._sentry.reraise(e)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2190, in upload_file
    response.raise_for_status()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/ada4321/DiffHPE/3tnqz9l7/wandb-metadata.json?Expires=1689059815&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ocx0ArZEc3dNodUf8qGD19DvFjuCUMa%2B%2BvT2w8TlMgxWP5%2B7gg2IPBZmkNarNgv6BPwn0MylngIEN5qrxpQkkzj%2BY6lIWmNPJ4wZJ%2F08xUAxjP4ViERLB0%2FkqCfPtJUBqbgC3S%2FbkLQhg0xwiWBsDP7qhdJYDxn30w%2BYwJV4iEwwxEScBw5NUGwq%2Bxw4stTx%2FFf0EnTcxMPhn7mxluA3OYcnKFXTVJGiNrhIwfWj5lktcE07HYfzxggrj2C7NDNhHn7CP7g75Z6VCsyTypLJau9b2lDGiGKMKfOmEG0t3jZHR7f%2FFaJUCvjRmkVWQVF%2BJwNko6BPmTTNwbLusfRNAA%3D%3D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 288, in run_and_notify
    self._do_upload_sync(event)
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 57, in run
    self.push()
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/filesync/upload_job.py", line 127, in push
    self._api.upload_file_retry(
  File "/home/zhuhe/.conda/envs/diffhpe/lib/python3.9/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: <Response [404]>
2023-07-10 15:16:58,156 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:16:58,224 INFO    Thread-17 :39913 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_151652-3tnqz9l7/files/output.log
2023-07-10 15:17:03,157 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:17:08,158 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:17:10,592 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 15:17:10,592 DEBUG   SenderThread:39913 [sender.py:send_request():396] send_request: stop_status
2023-07-10 15:17:13,821 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:17:18,822 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:17:23,828 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:17:24,234 INFO    Thread-17 :39913 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/zhuhe/HPE-with-Diffusion/wandb/run-20230710_151652-3tnqz9l7/files/config.yaml
2023-07-10 15:17:25,592 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 15:17:25,592 DEBUG   SenderThread:39913 [sender.py:send_request():396] send_request: stop_status
2023-07-10 15:17:29,832 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:17:34,833 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:17:39,834 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:17:40,592 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 15:17:40,592 DEBUG   SenderThread:39913 [sender.py:send_request():396] send_request: stop_status
2023-07-10 15:17:45,825 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:17:50,826 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:17:54,474 DEBUG   SystemMonitor:39913 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-07-10 15:17:54,475 DEBUG   SenderThread:39913 [sender.py:send():369] send: stats
2023-07-10 15:17:55,592 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: stop_status
2023-07-10 15:17:55,593 DEBUG   SenderThread:39913 [sender.py:send_request():396] send_request: stop_status
2023-07-10 15:17:55,830 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:18:00,831 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: status_report
2023-07-10 15:18:05,832 DEBUG   HandlerThread:39913 [handler.py:handle_request():144] handle_request: status_report
